spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql:///student?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:com/wuyou/dao/*.xml